function m = electrode_montage()
% electrode_montage    Current experiment montage.

% Author: Ariel Tankus - Autogenerated for clusters.
% Created: 10.08.2005.

%    Cluster: Region: Channel:
m = {
      1,	'UNK',	2
      2,	'UNK',	3
      3: 4,	'UNK',	4
      5,	'UNK',	5
      6,	'UNK',	6
      7,	'UNK',	8
      8,	'UNK',	9
      9:10,	'UNK',	10
     11:12,	'UNK',	11
     13:14,	'UNK',	13
     15,	'UNK',	14
     16:17,	'UNK',	15
     18:19,	'UNK',	16
     20,	'UNK',	17
     21:22,	'UNK',	18
     23:24,	'UNK',	19
     25,	'UNK',	20
     26,	'UNK',	21
     27,	'UNK',	22
     28:29,	'UNK',	23
     30,	'UNK',	24
     31,	'UNK',	25
     32:33,	'UNK',	26
     34:35,	'UNK',	27
     36,	'UNK',	28
     37,	'UNK',	30
     38,	'UNK',	31
     39,	'UNK',	33
     40:41,	'UNK',	37
     42:43,	'UNK',	38
     44,	'UNK',	40
     45,	'UNK',	42
     46,	'UNK',	43
     47,	'UNK',	44
     48,	'UNK',	46
     49,	'UNK',	48
     50,	'UNK',	49
     51,	'UNK',	50
     52,	'UNK',	51
     53,	'UNK',	52
     54,	'UNK',	53
     55,	'UNK',	54
     56,	'UNK',	57
     57,	'UNK',	58
     58,	'UNK',	59
     59,	'UNK',	60
     60,	'UNK',	61
     61,	'UNK',	62
     62,	'UNK',	63
     63,	'UNK',	64
     64,	'UNK',	65
     65,	'UNK',	66
     66,	'UNK',	67
     67:68,	'UNK',	68
     69,	'UNK',	69
     70,	'UNK',	70
     71,	'UNK',	71
     72,	'UNK',	74
     73,	'UNK',	75
     74,	'UNK',	76
     75,	'UNK',	78
     76,	'UNK',	80
};
