python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type micro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type micro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type macro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type macro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type spike --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type micro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type micro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type macro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type macro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type spike --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type micro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type micro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type macro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type macro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type spike --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type micro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type micro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type macro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type macro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type spike --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type micro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type micro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type macro --filter raw --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type macro --filter high-gamma --overwrite
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type spike --filter raw --overwrite
