python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_11 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_11 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_25 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 482 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 482 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 502 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 502 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 505 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 505 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_13 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_13 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type macro --filter high-gamma
