python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_11 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_11 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_11 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_11 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_11 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_25 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_25 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_25 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_25 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 479_25 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 482 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 482 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 482 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 482 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 482 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 499 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 499 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 499 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 499 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 499 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 502 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 502 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 502 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 502 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 502 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 505 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 505 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 505 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 505 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 505 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 513 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 513 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 513 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 513 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 513 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 515 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 515 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 515 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 515 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 515 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 538 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 538 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 538 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 538 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 538 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 540 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 540 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 540 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 540 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 540 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 541 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 541 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 541 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 541 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 541 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 543 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 543 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 543 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 543 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 543 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 545 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 545 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 545 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 545 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 545 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 549 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 549 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 549 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 549 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 549 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 551 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 551 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 551 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 551 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 551 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 552 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 552 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 552 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 552 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 552 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 553 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 553 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 553 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 553 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 553 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_4 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_4 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_4 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_4 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_4 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_13 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_13 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_13 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_13 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 554_13 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 510 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 530 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 539 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 544 --data-type spike --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type micro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type micro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type macro --filter raw
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type macro --filter high-gamma
python3 /neurospin/unicog/protocols/intracranial/syntax_single_unit/code/analyses/generate_raw__.py --patient 556 --data-type spike --filter raw
