function [] = LANG_RUN_ME()
% LANG_RUN_ME    

% Author: Ariel Tankus.
% Created: 31.01.2017.


LANG_SENTENCES_TEXT;
LANG_AUDIO_SENTENCES;
LANG_SENTENCES_TEXT(true);
LANG_AUDIO_SENTENCES(1);
LANG_SENTENCES_TEXT(true);
LANG_AUDIO_SENTENCES(2);
